services:
  vde:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vde
    image: vde:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./data:/app/data
      - ./subject:/app/subject
      - ./samples:/app/samples
    command: python main.py
