version: "3.9"

services:
  reverse_image_search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vde
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./data:/app/data
    command: python main.py
